Models/ErrorViewModel.cs
namespace efcoreApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CourseController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class CourseController: Controller
    {
        private readonly DataContext _context;
        public CourseController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var courses =await _context.Courses.ToListAsync();
            return View(courses);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Course model)
        {
            _context.Courses.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = await _context.Courses.Include(k => k.CourseRegisters)
                .ThenInclude(k => k.Student).FirstOrDefaultAsync(k => k.CourseId == id);

            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int? id, Course model)
        {
            if (id != model.CourseId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Courses.Any(o => o.CourseId == model.CourseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = await _context.Courses.FindAsync(id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Controllers/CourseRegisterController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace efcoreApp.Controllers
{
    public class CourseRegisterController:Controller
    {
        private readonly DataContext _context;
        public CourseRegisterController(DataContext context)
        {
            _context = context; 
        }
        public async Task<IActionResult> Index()
        {
            //include önemli!
            var courseRegisters = await _context.CourseRegisters.Include(x => x.Student).Include(x => x.Course).ToListAsync();
            return View(courseRegisters);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Students = new SelectList(await _context.Students.ToListAsync(),"StudentId","NameSurname");
            ViewBag.Courses = new SelectList(await _context.Courses.ToListAsync(), "CourseId","Title");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CourseRegister model)
        {
            model.RegisterDate = DateTime.Now;
           _context.CourseRegisters.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
            
        }
    }
}

Controllers/HomeController.cs
using efcoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace efcoreApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentController.cs
using efcoreApp.Data;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.Eventing.Reader;

namespace efcoreApp.Controllers
{
    public class StudentController : Controller
    {
        private readonly DataContext _context;
        public StudentController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Student model)
        {
            _context.Students.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _context.Students.Include(o => o.CourseRegisters)
                .ThenInclude(o => o.Course).FirstOrDefaultAsync(o => o.StudentId ==id);

            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int? id, Student model)
        {
            if (id != model.StudentId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Students.Any(o => o.StudentId == model.StudentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _context.Students.FindAsync(id);

            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var student = await _context.Students.FindAsync(id);
            if(student == null)
            {
                return NotFound();
            }
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
              
    }
}

        

Views/Course/Create.cshtml
@model Course

<h2>Add Course</h2>
<hr>
<form asp-controller="Course" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Title" class="form-label">Title</label>
        <input asp-for="Title" class="form-control">
    </div>

    <button type="submit" class="btn btn-secondary">Submit</button>

</form>

Views/Course/Delete.cshtml
@model Course

<p>
    <b>@Model.Title</b> isimli kursu silmek istiyor musunuz?

    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.CourseId">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a asp-action="Index" class="btn btn-primary">No</a>
    </form>
</p>

Views/Course/Edit.cshtml
@model Course

<h2>Edit Course</h2>
<hr>

<div class="row">
    <div class="col-8">
        <form asp-controller="Course" asp-action="Edit" method="post">
            <input type="hidden" asp-for="CourseId">
            <div class="mb-3">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control">
            </div>

            <button type="submit" class="btn btn-secondary">Submit</button>

        </form>
    </div>
    <div class="col-4">
        <h4>Students</h4>
        <hr>
        <ul>
            @foreach(var item in @Model.CourseRegisters)
            {
                <li>@item.Student.NameSurname</li>
            }
        </ul>
          
    </div>
   
</div>

Views/Course/Index.cshtml
@model IEnumerable<Course>
<h2>Course List</h2>
<a href="/Course/Create" class="btn btn-primary">Add Course</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.CourseId)</th>
            <th>@Html.DisplayNameFor(m => m.Title)</th>            
            <th></th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.CourseId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.CourseId" class="btn btn-sm btn-danger">Delete</a>
                </td>

            </tr>
        }
    </tbody>
</table>

Views/CourseRegister/Create.cshtml
@model CourseRegister

<h2>Add Course Register</h2>
<hr>
<form asp-controller="CourseRegister" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="StudentId" class="form-label">Student</label>
        <select asp-for="StudentId" asp-items="ViewBag.Students" class="form-control">
            <option value="">Choose</option>
        </select>

        
    </div>
    <div class="mb-3">
        <label asp-for="CourseId" class="form-label">Course</label>
        <select asp-for="CourseId" asp-items="ViewBag.Courses" class="form-control">
            <option value="">Choose</option>
        </select>
       

    </div>
    
    <button type="submit" class="btn btn-secondary">Submit</button>

</form>

Views/CourseRegister/Index.cshtml
@model IEnumerable<CourseRegister>

<h2>Registration List</h2>
<a asp-action="Create" class="btn btn-primary">Add Registration</a>
<hr>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.RegisterId)</th>
            @* Tablolar arası join işlemi yapıyoruz ikisini birleştirmek için!!! *@
            <th>@Html.DisplayNameFor(m => m.Student.StudentName)</th>
            <th>@Html.DisplayNameFor(m => m.Course.Title)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Student.StudentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Title)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.CourseId" class="btn btn-sm btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.CourseId" class="btn btn-sm btn-danger">Delete</a>
                </td>

            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>You can make your course registration here</a>.</p>
</div>
    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - efcoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/efcoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">efcoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CourseRegister" asp-action="Index">Course Registers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - efcoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model Student

<h2>Add Student</h2>
<hr>    
<form asp-controller="Student" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="StudentName" class="form-label">Student Name</label>
        <input asp-for="StudentName" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="StudentSurname" class="form-label">Student Surname</label>
        <input asp-for="StudentSurname" class="form-control">
    </div>
    <div class="mb-3">  
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" class="form-control">
    </div>
    
    <button type="submit" class="btn btn-secondary">Submit</button>

</form>

Views/Student/Delete.cshtml
@model Student

<p>
    <b>@Model.StudentName @Model.StudentSurname</b> isimli öğrenciyi silmek istiyor musunuz?

    <form asp-action="Delete" method="post">
        <input type="hidden" name="id" value="@Model.StudentId">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a asp-action="Index" class="btn btn-primary">No</a>
    </form> 
</p>

Views/Student/Edit.cshtml
@model Student

<h2>Student Update</h2>
<hr>

<div class="row">
    <div class="col-8">
        <form asp-controller="Student" asp-action="Edit" method="post">
            <input type="hidden" asp-for="StudentId">
            <div class="mb-3">
                <label asp-for="StudentName" class="form-label">Student Name</label>
                <input asp-for="StudentName" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="StudentSurname" class="form-label">Student Surname</label>
                <input asp-for="StudentSurname" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Phone" class="form-label">Phone</label>
                <input asp-for="Phone" class="form-control">
            </div>

            <button type="submit" class="btn btn-secondary">Submit</button>

        </form>
    </div>
    <div class="col-4">
        <h4>Courses</h4>
        <hr>
        <ul>
            @foreach(var item in Model.CourseRegisters)
            {
                <li>@item.Course.Title</li>
            }
        </ul>
    </div>
</div>

Views/Student/Index.cshtml
@model IEnumerable<Student>
<h2>Student List</h2>
<a href="/Student/Create" class="btn btn-primary">Add Student</a>
    <hr>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m.StudentId)</th>
                <th>@Html.DisplayNameFor(m => m.StudentName)</th>
                <th>@Html.DisplayNameFor(m => m.StudentSurname)</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentSurname)
                </td>
                <td>
                     <a asp-action="Edit" asp-route-id="@item.StudentId" class="btn btn-sm btn-primary">Edit</a>
                     <a asp-action="Delete" asp-route-id="@item.StudentId" class="btn btn-sm btn-danger">Delete</a>
                </td>

                </tr>
            }   
        </tbody>
    </table>